    
name: base
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.0.1
  - python=3.8.8
  - r-dplyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - r-plotly
  - r-stringr
  - r-caret
  - r-ellipse
  - r-e1071
  - r-kernlab
  - r-randomForest
  - pip
  - pip:
    - plotly
    - pandas
    - matplotlib
    - scikit-learn
    - numpy
    - scipy
